name: streamlitapp
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - streamlit=1.38.0
  - pandas=2.2.2
  - numpy=1.26.4
  - scipy=1.11.4
  - xgboost=2.0.3
  - flask=3.0.3
  - sqlalchemy=2.0.30
  - jinja2=3.1.4
  - markupsafe=2.1.5
  - packaging=24.1
  - cachetools=5.3.3
  - protobuf=4.25.3
  - requests
  - tqdm
  - pip:
      - google-generativeai==0.7.2
      - landingai-ade==0.2.5
      - python-dotenv==1.0.1
